chore: add agenty-flowcharting-panel plugin to eks
nuuday/terraform-k8s-grafana pull request #22
Opened 2021-09-15 13:20 UTC by jsnns-nuuday

Made it possible to add it for both, but only add it for eks (which the request was for).

2021-09-15 13:24 UTC, scoof requested changes

2021-09-15 13:24 UTC, scoof commented on grafana-eks/main.tf
> +  plugins       = ["agenty-flowcharting-panel"]
I don't think the CSP-specific modules should be installing different things. If you want differences between EKS and AKS, that belongs in terraform-managed-k8s

2021-09-15 13:58 UTC, jsnns-nuuday commented on grafana-eks/main.tf
> +  plugins       = ["agenty-flowcharting-panel"]
Ok, I have added plugins as a variable parameter to the module and set it in terraform-managed-k8s instead.

2021-09-16 12:21 UTC, scoof approved these changes

2021-09-16 12:28 UTC, merged